{{- if eq .Values.ephemeral false }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "knote-demo.app-name" . }}
  labels:
    {{- include "knote-demo.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
  - key:  {{ .Values.application.secrets.db_url.key }}
    name: {{ .Values.application.secrets.db_url.name }}
    property: {{ .Values.application.secrets.db_url.property }}
    version: {{ .Values.application.secrets.db_url.version }}
{{ end }}
