{{- if eq .Values.ephemeral true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knote-demo.app-name" . }}
  labels:
    {{- include "knote-demo.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_URL: {{ .Values.application.secrets.MONGO_URL | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.application.secrets.MINIO_ACCESS_KEY | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.application.secrets.MINIO_SECRET_KEY | b64enc }}
{{ end }}
