apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-lb
  labels:
    {{- include "knote-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "knote-demo.app-name" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.application.port }}
  type: LoadBalancer
