version: "3.1"

volumes:
  mongo-data:
  minio-data:

services:
  app:
    image: app:latest
    build: .
    container_name: app
    command: npm run start
    env_file: 
      - .env
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - mongo
      - minio
    volumes:
      - /app/node_modules
      - ./:/app/
    restart: always
  
  minio:
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: mykey
      MINIO_SECRET_KEY: mysecret
    command: ["minio", "server", "/storage"]
    volumes:
      - minio-data:/storage
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
