{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.minio.storage.class }}
  resources:
    requests:
      storage: {{ .Values.minio.storage.size }}
{{ end }}
